# Generated by Django 5.0.2 on 2024-02-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreview',
            old_name='date',
            new_name='created_date',
        ),
    ]
