# Generated by Django 5.0.2 on 2024-02-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreview',
            name='room',
        ),
        migrations.AddField(
            model_name='roomreview',
            name='room',
            field=models.ManyToManyField(to='room.room'),
        ),
    ]
