# Generated by Django 5.0.2 on 2024-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_roomreview_room_roomreview_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
