# Generated by Django 5.0.2 on 2024-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_adults_room_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
